import {Product} from './Product';
export const Data: Product[] = [
    {
        id:1,
        name: "Sản phẩm 1",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:2,
        name: "Sản phẩm 2",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:3,
        name: "Sản phẩm 3",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:4,
        name: "Sản phẩm 4",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:5,
        name: "Sản phẩm 5",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:6,
        name: "Sản phẩm 6",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:7,
        name: "Sản phẩm 7",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:8,
        name: "Sản phẩm 8",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:9,
        name: "Sản phẩm 9",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    },
    {
        id:10,
        name: "Sản phẩm 10",
        price: 1000,
        desc: "Mô tả sản phẩm",
        img: 'http://placehold.it/700x400',
        status: true,
    }

]
